### ISSUE TITLE
Assignment2 파트분배

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#1]
안녕하세요! 저는 master 최정인입니다! assignment2의 파트분배를 하겠습니다!
선민이가 함수 1,2번을 담당해주고 수진이가 함수 3,4번을 담당해주고 미옥이가 함수 5,6번을 담당해주면 제가 함수 7,8번을 만들겠습니다!!

**Comment by sunminxxi** [comment]
지금 바로 함수 1, 2번을 추가하도록 하겠습니다. _선민

**Comment by limmiok** [comment]
넵 알겠습니다!!_미옥

**Comment by soooojinn** [comment]
넹 함수 3,4번 잘해볼게요

**Comment by choijungp** [comment]
넵! 모두 확인하였으니까 issue를 닫겠습니다!!
