### ISSUE TITLE
함수 5,6번 수정해야할 것같습니다.

### ISSUE THREAD

**Issue by limmiok** [choijungp/Assignment2#14]
아!!!!!!!!!!!!!~~!!!!! 함수 5,6번에 &제거하고 다시 수정하겠습니다ㅠㅠㅠㅠㅠㅠ!!

**Comment by choijungp** [comment]
넹! 똑바로 해주세요~~~*^^*

**Comment by sunminxxi** [comment]
지금 알아서 다행입니다. 어허......ㅎㅎ

**Comment by soooojinn** [comment]
알겠습니당

**Comment by limmiok** [comment]
네ㅠㅠㅠ 빠른시일내로 수정본 올리겠습니다ㅠㅠㅠㅠ!!!!
