### ISSUE TITLE
Assignment2 함수 7 datecmp

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#17]
제가 지금 함수 7번 datecmp함수를 만들고 있는데요ㅜㅜ
void datecmp(void)
{
   int month1 = time1.tm_mon + 1;
   int month2 = time2.tm_mon + 1;
   int date1 = time1.tm_mday;
   int date2 = time2.tm_mday;

   printf("date compare\n");
   if (month1 < month2)
      printf("text1 is early\n")
   else if (month2 < month1)
      printf("text2 is early\n");
   else
   {
      if (date1 < date2)
         printf("text1 is early\n");
      else if (date2 > date1)
         printf("text2 is early\n");
      else
         printf("same date\n");
   }
   printf("\n");
}
 이렇게 하면 괜찮을까요??

**Comment by sunminxxi** [comment]
엄훠나,,,,,,,, printf("text1 is early\n") 
세미콜론,,,,,,, 사라졌다..
붙여주어여.....

**Comment by choijungp** [comment]
헉!! 넵넵!! 세미콜론 붙이겠습니다ㅜㅜ

**Comment by limmiok** [comment]
잘합시다 정인씨!!!!!!!!!!!!!!!!!!!

**Comment by soooojinn** [comment]
마지막 else if의 조건문에서 부등호 방향을 바꿔줘야 할 것 같습니다

**Comment by choijungp** [comment]
헉ㅜㅜ 그렇네요ㅠㅜ 그것까지 수정해서 다시 issue에 올려볼께요ㅠㅠ
