### ISSUE TITLE
Assignment2 함수 7 datecmp함수 오류 수정!

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#18]
void datecmp(void)
{
   int month1 = time1.tm_mon + 1;
   int month2 = time2.tm_mon + 1;
   int date1 = time1.tm_mday;
   int date2 = time2.tm_mday;

   printf("date compare\n");
   if (month1 < month2)
      printf("text1 is early\n");
   else if (month2 < month1)
      printf("text2 is early\n");
   else
   {
      if (date1 < date2)
         printf("text1 is early\n");
      else if (date2 < date1)
         printf("text2 is early\n");
      else
         printf("same date\n");
   }
   printf("\n");
}

오류 수정했습니다! 또 다른 오류가 있으면 말씀해주세요ㅠㅠ

**Comment by sunminxxi** [comment]
와우 완벽스~~~~~~~~~~~~~~~~~~~

**Comment by soooojinn** [comment]
와우 너무 완벽해요~~~~~

**Comment by limmiok** [comment]
완벽해요오오오옹!! !!!!!!!!!!!!!!!!!!!!!!1

**Comment by choijungp** [comment]
그럼 이제 oss.c에 추가 할께엽
