### ISSUE TITLE
Assignment2 _ 8번함수 코드 확인해주세요!!

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#20]
void timecmp(void)
{
   printf("time compare\n");

   if (time2.tm_hour < time1.tm_hour)
      printf("text1 is early\n");
   else if (time1.tm_hour < time1.tm_hour)
      printf("text2 is early\n");
   else
   {
      if (time2.tm_min < time1.tm_min)
         printf("text1 is early\n");
      else if (time1.tm_min < time2.tm_min)
         printf("text2 is early\n");
      else
         printf("same time\n");
   }
   printf("\n");
}

8번함수 timecmp함수 만들었습니다! 다들 확인 한번씩 부탁드려용!!

**Comment by sunminxxi** [comment]
워매..... 조건문의 조건들의 부등호들이.....청개구리인가여

**Comment by soooojinn** [comment]
조건문이 이상한거 같아요ㅠㅠ수정해주세용

**Comment by choijungp** [comment]
헉ㅜㅜ 죄송해요ㅜㅜ 다시 수정해서올릴께요ㅜㅜ
