### ISSUE TITLE
Assignment2 _8번함수 부등호 오류 수정!

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#21]
void timecmp(void)
{
   printf("time compare\n");

   if (time2.tm_hour > time1.tm_hour)
      printf("text1 is early\n");
   else if (time1.tm_hour > time1.tm_hour)
      printf("text2 is early\n");
   else
   {
      if (time2.tm_min > time1.tm_min)
         printf("text1 is early\n");
      else if (time1.tm_min > time2.tm_min)
         printf("text2 is early\n");
      else
         printf("same time\n");
   }
   printf("\n");
}
 
부등호 수정했습니다ㅜㅜ 다시 한 번만 확인해주세요ㅜㅜ

**Comment by soooojinn** [comment]
오오 이제 다 맞는거같아요 수고하셨습니당~~~~~~~!

**Comment by sunminxxi** [comment]
이제...부등호 다 맞네여.ㅎㅎㅎㅎㅎ

**Comment by choijungp** [comment]
그럼 이제 oss.c에 추가할께요!! 모두 수고하셨습니당ㅎㅎ
