### ISSUE TITLE
Assignment2 완성!!

### ISSUE THREAD

**Issue by choijungp** [choijungp/Assignment2#22]
여러분!! 저희 Assignment2 코드 완성했습니다!!!!!!
모두모두 수고하셨습니다! 다들 한번 코드 확인해주세요!!*^^*

**Comment by soooojinn** [comment]
정말 너무 완벽합니다
다들 진짜 수고하셨습니다ㅠㅠㅠㅠㅠㅠ

**Comment by sunminxxi** [comment]
넘나 수고하셨습니다ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
코드 확인해 보겠습니다...이미 완벽하지만..ㅎ
