### ISSUE TITLE
원본 struct tm부분 고쳐야할것 같아요!

### ISSUE THREAD

**Issue by limmiok** [choijungp/Assignment2#8]
struct tm *time1, *time2를 struct tm time1, time2로 바꿔줘야할 것 같아요!!

**Comment by choijungp** [comment]
아! 그렇네요!! 감사합니다!!얼른 수정해보겠습니다 ㅎㅎ

**Comment by limmiok** [comment]
제가 수정해서 올릴게용!!!!ㅎㅎㅎ

**Comment by choijungp** [comment]
헉!! 넵넵 감사합니당ㅎㅎ
